const express = require("express");
const router = express.Router();
const taskController = require("../controllers/taskController");
const { verifyToken } = require("../middleware/authMiddleware");

router.get("/my-tasks", verifyToken, taskController.getMyAllTasks);
router.get("/group/:groupId", verifyToken, taskController.getGroupTasks);
router.post("/group/:groupId", verifyToken, taskController.createTask);
router.put("/:taskId", verifyToken, taskController.updateTask);
router.get("/:taskId", verifyToken, taskController.getTaskDetail);
router.post("/assign", verifyToken, taskController.assignTask);
router.put("/:taskId/view", verifyToken, taskController.markViewed);
router.put("/:taskId/complete", verifyToken, taskController.markCompleted);
router.put("/:taskId/pin", verifyToken, taskController.togglePinTask);
router.post("/:taskId/vote", verifyToken, taskController.votePoll);
router.post("/:taskId/options", verifyToken, taskController.addPollOption);
router.put("/:taskId/close-poll", verifyToken, taskController.closePoll);
router.post("/:taskId/remind", verifyToken, taskController.remindTask);
router.put("/:taskId/attendance-report", verifyToken, taskController.updateAttendanceReport);
router.get("/:taskId/attendance-report/parse", verifyToken, taskController.parseAttendanceReport);
router.post("/:taskId/checkout", verifyToken, taskController.checkoutMeeting);
router.get("/:taskId/meeting-attendances", verifyToken, taskController.getMeetingAttendances);
module.exports = router;